#数据库连接信息
jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/demo
  username: root
  password:
#Mybatis
mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
entity_package: com.imooc.wechatdemo.pojo